apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: taskprocessor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskprocessor
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 85